name: chtc-wrmxpress
# conda env create -f conda_env.yml

channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda

dependencies:
  - cython=0.29.21
  - gtk2=2.24.32
  - imageio=2.9.0
  - matplotlib=3.3.3
  - mysqlclient=1.4.6
  - networkx=2.5
  - numpy=1.21.4
  - opencv=4.5.0
  - openjdk=8.0.302
  - pandas=1.1.3
  - pathlib=1.0.1
  - pillow=8.4.0
  - python=3.8.5
  - pyWavelets=1.1.1
  - r-base=4.0.3
  - r-tidyverse=1.3.0
  - r-tidymodels=0.1.4
  - r-xgboost=1.5.0
  - r-janitor=2.1.0
  - scipy=1.5.3
  - tifffile=2020.11.18
  - vim=8.2.2041
  - wxpython=4.1.0
  - pyyaml=5.4.1
  - pip=21.3.1
  - centrosome=1.2.0
  - scikit-image=0.19.1
  - cellprofiler=4.2.1
