########################################
######### INSTRUMENT SETTINGS  #########
########################################

# single-well: each image includes only one well
# multi-well: each image contains multiple wells
imaging_mode:
  # - single-well
  - multi-well

file_structure:
  # - imagexpress
  - avi

# Number of rows/columns in the multi-well image (require multi-well mode)
multi-well-row: 4
multi-well-cols: 6

# Should wrmXpress auto-detect wells, or should the image be split into a grid
# based on the width/height of the image?
multi-well-detection:
  - auto
  # - grid

#####################################
######### WORM INFORMATION  #########
#####################################

species:
  - Bma
  # - Cel
  # - Sma

stages:
  # - Mf
  - Adult
  # - Mixed

#####################################
######### MODULE SELECTION  #########
#####################################

modules:

  #### Motilty (optical flow) ####
  motility:
    run: True

  #### Conversion ####
  # For converting the TimePoint directory structure used for timelapse/video
  # experiments to a directory that can be loaded as a stack in Fiji. Will
  # automatically be set to run = True if flow[run] = True. If the converted
  # video should be saved in directories[output], set save_video to True and
  # add a rescale_multiplier (can be any float value). Flow will be run with the
  # unscaled video, but the saved video can still be scaled.
  convert:
    run: False
    save_video: False
    rescale_multiplier: 1

  #### Segmentation ####
  # If there is only one wavelength, keep the value blank. If there are multiple,
  # uncomment the wavelength you want segmented.
  segment:
    run: True
    wavelength:
      # - w1
      # - w2
      # - w3

  #### CellProfiler ####
  # Change run to True and uncomment a pipeline.
  cellprofiler:
    run: False
    pipeline:
      - wormsize_intensity_cellpose
      # - mf_celltox
      # - feeding
      # - wormsize
      # - wormsize_trans

  #### Diagnostics ####
  # Usually set to true.
  dx:
    run: True

######################################
######### RUN-TIME SETTINGS  #########
######################################

# Run on a subset of wells; 'All' will auto-populate wells using the input data
wells:
  - A01
  - A02

directories:
  work:
    - work
  input:
    - input
  output:
    - output
